import {
  Combine,
  FileArchive,
  FileImage,
  FileText,
  ImagePlus,
  Layers,
  LockKeyhole,
  Scissors,
  ShieldCheck,
} from "lucide-react";

export const MAX_FILE_SIZE_MB = 100;
export const MAX_FILE_COUNT = 20;

export const tools = [
  {
    id: "compress",
    title: "Compress PDF",
    endpoint: "/compress",
    icon: FileArchive,
    accept: ".pdf,application/pdf",
    allowedExtensions: [".pdf"],
    multiple: false,
    output: "compressed.pdf",
    description: "Reduce file size with image recompression and PDF stream cleanup.",
    fields: [{ name: "quality", label: "Image quality", type: "range", min: 20, max: 85, defaultValue: 55 }],
  },
  {
    id: "merge",
    title: "Merge PDFs",
    endpoint: "/merge",
    icon: Combine,
    accept: ".pdf,application/pdf",
    allowedExtensions: [".pdf"],
    multiple: true,
    minFiles: 2,
    output: "merged.pdf",
    description: "Combine multiple PDFs into one ordered document.",
  },
  {
    id: "split",
    title: "Split PDF",
    endpoint: "/split",
    icon: Scissors,
    accept: ".pdf,application/pdf",
    allowedExtensions: [".pdf"],
    multiple: false,
    output: "split-pages.zip",
    description: "Extract every page or custom ranges into separate PDFs.",
    fields: [{ name: "ranges", label: "Ranges", placeholder: "Example: 1-3,5,8-10", defaultValue: "" }],
  },
  {
    id: "rearrange",
    title: "Rearrange Pages",
    endpoint: "/rearrange",
    icon: Layers,
    accept: ".pdf,application/pdf",
    allowedExtensions: [".pdf"],
    multiple: false,
    output: "rearranged.pdf",
    description: "Create a new PDF with pages in your chosen order.",
    fields: [{ name: "order", label: "Page order", placeholder: "Example: 3,1,2,4", required: true, defaultValue: "" }],
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    endpoint: "/pdf-to-word",
    icon: FileText,
    accept: ".pdf,application/pdf",
    allowedExtensions: [".pdf"],
    multiple: false,
    output: "converted.docx",
    description: "Extract readable PDF text into an editable Word document.",
  },
  {
    id: "pdf-to-image",
    title: "PDF to Image",
    endpoint: "/pdf-to-image",
    icon: FileImage,
    accept: ".pdf,application/pdf",
    allowedExtensions: [".pdf"],
    multiple: false,
    output: "pdf-images.zip",
    description: "Export every PDF page as a high quality PNG image.",
    fields: [{ name: "dpi", label: "DPI", type: "number", min: 72, max: 300, defaultValue: 160 }],
  },
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    endpoint: "/image-to-pdf",
    icon: ImagePlus,
    accept: "image/png,image/jpeg,image/webp",
    allowedExtensions: [".png", ".jpg", ".jpeg", ".webp"],
    multiple: true,
    output: "images.pdf",
    description: "Turn JPG, PNG or WebP images into a clean PDF.",
  },
  {
    id: "watermark",
    title: "Add Watermark",
    endpoint: "/watermark",
    icon: ShieldCheck,
    accept: ".pdf,application/pdf",
    allowedExtensions: [".pdf"],
    multiple: false,
    output: "watermarked.pdf",
    description: "Stamp a transparent text watermark across every page.",
    fields: [
      { name: "text", label: "Watermark text", placeholder: "CONFIDENTIAL", required: true, defaultValue: "CONFIDENTIAL" },
      { name: "opacity", label: "Opacity", type: "range", min: 0.05, max: 0.75, step: 0.05, defaultValue: 0.18 },
    ],
  },
  {
    id: "protect",
    title: "Protect PDF",
    endpoint: "/protect",
    icon: LockKeyhole,
    accept: ".pdf,application/pdf",
    allowedExtensions: [".pdf"],
    multiple: false,
    output: "protected.pdf",
    description: "Encrypt a PDF with password protection.",
    fields: [{ name: "password", label: "Password", type: "password", placeholder: "Minimum 4 characters", required: true, defaultValue: "" }],
  },
];

export function initialFields(tool) {
  return Object.fromEntries((tool.fields || []).map((field) => [field.name, field.defaultValue ?? ""]));
}

