export const MAX_FILE_SIZE_MB = 100;

export const tools = [
  {
    id: "compress",
    title: "Compress PDF",
    endpoint: "/compress",
    icon: "file-tray-full-outline",
    multiple: false,
    output: "compressed.pdf",
    allowedExtensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    description: "Shrink a PDF while preserving readable quality.",
    fields: [{ name: "quality", label: "Image quality", type: "number", defaultValue: "55" }],
  },
  {
    id: "merge",
    title: "Merge PDFs",
    endpoint: "/merge",
    icon: "git-merge-outline",
    multiple: true,
    minFiles: 2,
    output: "merged.pdf",
    allowedExtensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    description: "Combine PDFs in selected order.",
  },
  {
    id: "split",
    title: "Split PDF",
    endpoint: "/split",
    icon: "cut-outline",
    multiple: false,
    output: "split-pages.zip",
    allowedExtensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    description: "Export every page or specific ranges.",
    fields: [{ name: "ranges", label: "Ranges", defaultValue: "", placeholder: "1-3,5,8-10" }],
  },
  {
    id: "rearrange",
    title: "Rearrange Pages",
    endpoint: "/rearrange",
    icon: "layers-outline",
    multiple: false,
    output: "rearranged.pdf",
    allowedExtensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    description: "Create a new PDF with a custom page order.",
    fields: [{ name: "order", label: "Page order", required: true, defaultValue: "", placeholder: "3,1,2,4" }],
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    endpoint: "/pdf-to-word",
    icon: "document-text-outline",
    multiple: false,
    output: "converted.docx",
    allowedExtensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    description: "Extract readable text into DOCX.",
  },
  {
    id: "pdf-to-image",
    title: "PDF to Image",
    endpoint: "/pdf-to-image",
    icon: "image-outline",
    multiple: false,
    output: "pdf-images.zip",
    allowedExtensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    description: "Export PDF pages as PNG images.",
    fields: [{ name: "dpi", label: "DPI", type: "number", defaultValue: "160" }],
  },
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    endpoint: "/image-to-pdf",
    icon: "images-outline",
    multiple: true,
    output: "images.pdf",
    allowedExtensions: [".png", ".jpg", ".jpeg", ".webp"],
    mimeTypes: ["image/png", "image/jpeg", "image/webp"],
    description: "Convert selected images into a PDF.",
  },
  {
    id: "watermark",
    title: "Add Watermark",
    endpoint: "/watermark",
    icon: "shield-checkmark-outline",
    multiple: false,
    output: "watermarked.pdf",
    allowedExtensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    description: "Stamp transparent text on every page.",
    fields: [
      { name: "text", label: "Watermark text", required: true, defaultValue: "CONFIDENTIAL" },
      { name: "opacity", label: "Opacity", type: "number", defaultValue: "0.18" },
    ],
  },
  {
    id: "protect",
    title: "Protect PDF",
    endpoint: "/protect",
    icon: "lock-closed-outline",
    multiple: false,
    output: "protected.pdf",
    allowedExtensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    description: "Encrypt a PDF with a password.",
    fields: [{ name: "password", label: "Password", required: true, secure: true, defaultValue: "" }],
  },
];

export function initialFields(tool) {
  return Object.fromEntries((tool.fields || []).map((field) => [field.name, field.defaultValue || ""]));
}
